# -*- coding: utf-8 -*-
"""2203A51653_Assignment1_part1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ve-euUGctrDsLbgFGUdDgYOGFZ9MeaW7
"""



import numpy as np
my_list = [1, 2, 3, 4, 5]

print(my_list)

print(type(my_list))

import matplotlib.pyplot as plt
import numpy as np

# Data
people = ['kiran', 'arun', 'vijay', 'varun']
age = [25, 30, 35, 40]
height = [145, 151, 165, 173]
weight = [45, 55, 65, 75]

# Scatter Plot
plt.figure(figsize=(10, 6))
plt.scatter(age, height, label='Height')
plt.scatter(age, weight, label='Weight')
plt.xlabel('Age')
plt.ylabel('Height/Weight')
plt.title('Scatter Plot: Age vs Height/Weight')
plt.legend()
plt.show()

# Bar Chart
x = np.arange(len(people))  # the label locations
width = 0.35  # the width of the bars

fig, ax = plt.subplots()
rects1 = ax.bar(x - width/2, height, width, label='Height')
rects2 = ax.bar(x + width/2, weight, width, label='Weight')

# Add some text for labels, title and custom x-axis tick labels, etc.
ax.set_xlabel('People')
ax.set_ylabel('Height/Weight')
ax.set_title('Bar Chart: People vs Height/Weight')
ax.set_xticks(x)
ax.set_xticklabels(people)
ax.legend()

fig.tight_layout()
plt.show()

# Histogram
plt.hist(height, bins=5, alpha=0.5, label='Height')
plt.hist(weight, bins=5, alpha=0.5, label='Weight')
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.title('Histogram: Height/Weight')
plt.legend(loc='upper right')
plt.show()

import numpy as np
my_array = np.array([1, 2, 3, 4, 5])


print(my_array)

print(type(my_array))

import numpy as np
print(type(my_list))

print(type(my_array))

import numpy as np

product = my_list * my_array

print(product)

quotient = my_array / my_list

print(quotient)

power = my_array ** my_list

print(power)

import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

sum_array = array1 + array2

print("Addition of Two: array1 + array2")

print(sum_array)

import numpy as np

x = np.array([1,2,3])
sin_x=np.sin(x)
log_x=np.log(x)
print(sin_x)
print(log_x)

import pandas as pd

df = pd.read_csv('/content/sample_data/california_housing_train.csv')

print(df.head())